version: '3.7'

services:
  api:
    image: seenlive:latest
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"      
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: SeenLiveDb
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes: 
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432